parameters:
  - name: DebugMode
    displayName: Run the Pipeline in Debug Mode
    type: boolean
    default: false

  - name: InstancesAmount
    displayName: How many instances will be generated
    type: string
    default: '5'

  - name: InstanceType
    displayName: The type of instance to generate
    type: string
    default: person


variables:
  - name: System.Debug
    value: ${{ parameters.DebugMode }}

  - name: iAmount
    value: ${{ parameters.InstancesAmount}}

  - name: iType
    value: ${{ parameters.InstanceType }}

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    displayName:  'Build' 
    jobs:
    - job: build
      displayName: build
      steps:

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
        displayName: Setting up Python

      - bash: pip install -r requirements.txt
        displayName: 'Installing pip requirements' 

      - bash: python ./src/app.py --instances ${{variables.iAmount}} --datatype ${{variables.iType}}

      - publish: ./output/output.json
        artifact: output.json

  # - stage: Run
  #   dependsOn: Build
  #   displayName: 'Run and Publish'
  #   jobs:
  #     - job: run
  #       displayName: run
  #       steps:

  #       - bash: python ./src/app.py --instances ${{variables.iAmount}} --datatype ${{variables.iType}}

  #       - publish: ./output/output.json
  #         artifact: output.json
    